# Generated by Django 4.2.7 on 2025-12-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=4)),
                ('startingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currentPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isBought', models.BooleanField()),
                ('sharesOwned', models.IntegerField()),
            ],
        ),
    ]
