# Generated by Django 4.2.7 on 2025-12-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_spot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='priceWhenBought',
            field=models.DecimalField(decimal_places=2, default=105.0, max_digits=10),
            preserve_default=False,
        ),
    ]
