# Generated by Django 4.2.7 on 2025-12-16 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_spot', '0002_stock_pricewhenbought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='currentPrice',
        ),
    ]
