# Generated by Django 4.2.7 on 2025-12-16 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_spot', '0003_remove_stock_currentprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscalDateEnding', models.DateField()),
                ('reportedDate', models.DateField()),
                ('reportedEPS', models.DecimalField(decimal_places=4, max_digits=10)),
                ('estimatedEPS', models.DecimalField(decimal_places=4, max_digits=10)),
                ('surprise', models.DecimalField(decimal_places=4, max_digits=10)),
                ('surprisePercentage', models.DecimalField(decimal_places=4, max_digits=10)),
                ('reportTime', models.CharField(max_length=10)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_earnings', to='stock_spot.stock')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscalDateEnding', models.DateField()),
                ('reportedEPS', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_earnings', to='stock_spot.stock')),
            ],
        ),
    ]
