# Generated by Django 4.2.7 on 2025-12-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_spot', '0004_quarterlyearning_annualearning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='priceWhenBought',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
