# Generated by Django 4.2.7 on 2025-12-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_spot', '0005_alter_stock_pricewhenbought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualearning',
            name='reportedEPS',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlyearning',
            name='estimatedEPS',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlyearning',
            name='reportedEPS',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlyearning',
            name='surprise',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlyearning',
            name='surprisePercentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
