# Generated by Django 4.2.7 on 2025-12-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_spot', '0006_alter_annualearning_reportedeps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='relativeStrengthIndex',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
