# Generated by Django 4.2.7 on 2025-12-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_spot', '0007_stock_relativestrengthindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='compoundedAnnualGrowthRate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='yoyEPSPercentGrowth',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
