# Generated by Django 4.2.7 on 2025-12-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_spot', '0008_stock_compoundedannualgrowthrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='startingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
