# Generated by Django 4.2.7 on 2025-12-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_spot', '0009_alter_stock_startingprice_alter_stock_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
