# Generated by Django 4.2.7 on 2025-12-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_spot', '0010_alter_stock_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='currentPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
