# Generated by Django 4.2.7 on 2025-12-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_spot', '0011_stock_currentprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='isBought',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sharesOwned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
