# Generated by Django 4.2.7 on 2026-01-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_spot', '0013_alter_stock_compoundedannualgrowthrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='companySummary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
