# Generated by Django 4.2.7 on 2026-01-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_spot', '0014_stock_companysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='conservativeCompanyValuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sharesOutstanding',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
