# Generated by Django 4.2.7 on 2026-01-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_spot', '0015_stock_conservativecompanyvaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='marketCap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
