# Generated by Django 4.2.7 on 2026-01-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_spot', '0016_stock_marketcap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='conservativeCompanyValuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
