# Generated by Django 4.2.7 on 2026-01-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_spot', '0017_alter_stock_conservativecompanyvaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='conservativeCompanyValuation',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
